// Domain enums. These used to be generated by Prisma; the database is gone, so
// they now live here as plain string unions. The values are the ones already
// stored in every user's local state — do not rename them.

export type TransactionType = "INCOME" | "EXPENSE";

export type AccountType = "CASH" | "DEBIT_CARD" | "SAVINGS" | "BROKERAGE";

export type CategoryKind = "INCOME" | "EXPENSE";

export type RecommendationSeverity = "INFO" | "SUCCESS" | "WARNING" | "CRITICAL";

export type SecurityRisk = "LOW" | "MEDIUM" | "HIGH";

export type RiskProfileCode = "CONSERVATIVE" | "MODERATE" | "AGGRESSIVE";

export type RecurrenceFrequency = "WEEKLY" | "MONTHLY" | "YEARLY";

export type LiabilityKind = "CREDIT_CARD" | "LOAN" | "MORTGAGE" | "INSTALLMENT" | "OTHER";
