"use client";

// Слова экрана «Таблица». Свой маленький словарь рядом с экраном, а не в общем
// каталоге: их много, и живут они только здесь.

import { useI18n } from "@/lib/i18n/context";
import type { SheetColumnKind } from "@/lib/sheet/model";

const RU = {
  main: "Основные",
  savings: "Сбережения",
  month: "Месяц",
  total: "Итог",
  savingsTotal: "Итог сбережений",
  sum: "Всего",
  average: "В среднем",
  addColumn: "Статья",
  addColumnTitle: "Добавить статью — новый столбец таблицы",
  addMonth: "Месяц",
  addMonthBefore: "Месяц раньше",
  import: "Перенести из Excel",
  export: "Выгрузить в Excel",
  exported: "Таблица выгружена.",
  compare: "Сравнить с учётом",
  compareHint: "Под числом — сколько на самом деле ушло по этой категории в учёте.",
  fact: "факт",
  undoImport: "Отменить перенос",
  undone: "Таблица вернулась как была до переноса.",
  showHidden: "Скрытые столбцы",
  fillDown: "Заполнить вниз",
  more: "Ещё",
  filled: "Заполнено до конца таблицы.",
  operations: "Операции в учёте",
  operationsFor: "Операции за {month}",
  emptyTitle: "Таблица бюджета по месяцам",
  emptyLead:
    "Как в Excel, только проще: месяцы — строками, статьи расходов — столбцами. Остаток и Итог таблица считает сама.",
  emptyStep1: "Выберите статьи",
  emptyStep1Text:
    "Продукты, транспорт, жильё — то, на что уходят деньги. Можно взять свои категории из учёта.",
  emptyStep2: "Впишите суммы",
  emptyStep2Text:
    "Сколько получаете и планируете тратить каждый месяц. Потом правьте прямо в клетках.",
  emptyStep3: "Смотрите итог",
  emptyStep3Text: "Что останется в конце месяца — таблица считает сама и переносит в следующий.",
  emptyCreate: "Создать таблицу",
  emptyStart: "Пустой лист",
  emptyImport: "Перенести мою таблицу из Excel",
  hint: "Двойное нажатие или любая цифра — ввод. Enter — вниз, Tab — вправо, Ctrl+V — вставить блок из Excel, Ctrl+Z — отменить.",
  // Панель выбранной клетки
  barEmpty: "Нажмите на клетку и впишите сумму. Можно формулу: 20000+1500.",
  barCell: "{column} · {month}",
  barFact: "По учёту: {fact}",
  barOver: "больше на {amount}",
  barUnder: "меньше на {amount}",
  barNextMonth: "На следующий месяц",
  barAuto: "Посчитано само: {value}. Впишите число, чтобы поправить.",
  barPlaceholder: "Число или формула",
  barInputLabel: "Ввод в выбранную клетку",
  // Сводка месяца
  sumTitle: "Сейчас · {month}",
  sumNow: "Сейчас",
  sumOpening: "На начало",
  sumIncome: "Доходы",
  sumExpense: "Расходы",
  sumTotal: "Останется",
  sumSavings: "В сбережениях",
  shortfall: "В {month} денег не хватит: итог {amount}. Уменьшите расходы или добавьте доход.",
  runningOut: "Таблица кончается через {count} мес. — добавьте ещё месяцев.",
  // Месяцы и заполнение
  addMonths: "Месяцы",
  addOne: "+1 месяц вперёд",
  addThree: "+3 месяца вперёд",
  addYear: "+12 месяцев вперёд",
  monthsAdded: "Добавлено месяцев: {count}.",
  today: "К текущему месяцу",
  fillFromLedger: "Заполнить по учёту",
  fillFromLedgerHint:
    "В прошедшие месяцы подставится то, что записано в учёте. Только в пустые клетки статей, у которых есть категория.",
  fillFromLedgerDone: "Подставлено из учёта: {count}.",
  fillFromLedgerNothing:
    "Подставлять нечего: у статей нет категорий или в учёте за эти месяцы пусто.",
  monthActions: "Что сделать с месяцем",
  monthOperations: "Операции за месяц",
  copyFromPrev: "Скопировать числа из прошлого месяца",
  copied: "Скопировано: {count}.",
  copyNothing: "В прошлом месяце нечего копировать.",
  clearMonth: "Очистить числа месяца",
  cleared: "Очищено: {count}.",
  density: "Размер",
  densityComfort: "Крупно",
  densityCompact: "Компактно",
  // Справка
  help: "Как это работает",
  helpItems: [
    "Строка — месяц, столбец — статья: сколько вы потратили или планируете потратить.",
    "Курсивом — то, что таблица посчитала сама. Остаток равен итогу прошлого месяца.",
    "Итог = Остаток + Доходы − Расходы − В сбережения. Он переходит в Остаток следующего месяца.",
    "Вписывайте число или формулу: 20000+1500, =СУММ(1000;2000), =45000*13%.",
    "Нажмите на название статьи с категорией — откроются её операции в учёте.",
    "Внизу — сумма и среднее по каждой статье."
  ],
  helpLegend: "Обозначения",
  legendAuto: "посчитано само",
  legendIncome: "доход",
  legendMinus: "не хватает",
  legendNow: "текущий месяц",
  // Мастер создания
  wizTitle: "Создать таблицу",
  wizLead: "Ответьте на несколько вопросов — таблица соберётся сама. Всё можно поменять потом.",
  wizFrom: "С какого месяца",
  wizFromNow: "С этого месяца",
  wizFromAgo1: "С прошлого месяца",
  wizFromAgo3: "3 месяца назад",
  wizFromAgo6: "Полгода назад",
  wizFromAgo12: "Год назад",
  wizMonths: "Сколько месяцев",
  wizMonthsCount: "{count} мес.",
  wizOpening: "Сколько денег сейчас",
  wizOpeningHint: "Всё, что на картах и наличными, — с этого начинается таблица.",
  wizIncome: "Доход в месяц",
  wizIncomeHint: "Зарплата и прочее. В любом месяце потом можно поменять.",
  wizArticles: "Статьи расходов",
  wizArticlesHint:
    "Отметьте, что учитывать. Справа — сколько планируете в месяц (можно не заполнять).",
  wizMonthly: "в месяц",
  wizAll: "Выбрать все",
  wizNone: "Снять все",
  wizSavings: "Вести сбережения (подушку)",
  wizSavingsOpening: "Уже накоплено",
  wizHistory: "Подставить прошлые месяцы из учёта",
  wizHistoryHint: "Для месяцев до нынешнего возьмём то, что записано в приложении.",
  wizCreate: "Создать таблицу",
  wizCreated: "Таблица готова: {months} мес., статей: {count}.",
  // Режим «По месяцам» на телефоне
  viewTable: "Таблица",
  viewMonths: "По месяцам",
  monthPrev: "Прошлый месяц",
  monthNext: "Следующий месяц",
  monthTotalRow: "Останется",
  monthEmptyCell: "не заполнено",
  monthEditHint: "Нажмите на статью, чтобы вписать сумму.",
  kindHints: {
    opening: "С чего начинается месяц. Обычно считается само из итога прошлого месяца.",
    income: "Деньги, которые приходят: зарплата, подработка.",
    expense: "Деньги, которые уходят: продукты, транспорт, жильё.",
    toSavings: "Перевод из основных денег в копилку. Из итога вычитается.",
    fromSavings: "Снятие из копилки в основные деньги.",
    savingsOpening: "Сколько в копилке на начало месяца.",
    savingsIncome: "Проценты по вкладу: копилка растёт, из основных денег не вычитается.",
    note: "Просто слова — комментарий к месяцу. Ничего не считает."
  } satisfies Record<SheetColumnKind, string>,
  cellError: "Не посчиталось: {error}",
  auto: "посчитано из прошлого месяца",
  save: "Сохранить",
  clear: "Очистить",
  cancel: "Отмена",
  close: "Закрыть",
  delete: "Удалить",
  column: "Столбец",
  columnNew: "Новый столбец",
  columnName: "Название",
  columnKind: "Что это",
  columnCategory: "Категория в учёте",
  noCategory: "Без категории",
  moveLeft: "Левее",
  moveRight: "Правее",
  hide: "Скрыть",
  unhide: "Показать",
  deleteColumn: "Удалить столбец",
  deleteColumnConfirm: "Удалить столбец «{name}» и все его числа?",
  deleteMonth: "Удалить строку",
  deleteMonthConfirm: "Удалить {month} из таблицы?",
  targets: "Цели",
  addTarget: "Цель",
  targetLabel: "Название",
  targetDefault: "Подушка",
  targetDate: "К какой дате",
  targetAmount: "Сумма",
  targetBy: "{label} к {date}: {amount}",
  targetReached: "по таблице будет {amount} — цель достигнута",
  targetOnTrack: "{month}: в сбережениях будет {amount}; до цели — по {perMonth} в месяц",
  targetNoRows: "добавьте месяцы до этой даты — таблица посчитает, хватит ли",
  input: "Число или формула",
  inputHint: "Можно как в Excel: 20000+1500, =СУММ(1000;2000), =45000*13%",
  saved: "Сохранено.",
  pasted: "Вставлено: {count}.",
  kinds: {
    opening: "Остаток на начало",
    income: "Доход",
    expense: "Расход",
    toSavings: "В сбережения",
    fromSavings: "Из сбережений",
    savingsOpening: "Подушка на начало",
    savingsIncome: "Проценты по вкладу",
    note: "Заметка (текст)"
  } satisfies Record<SheetColumnKind, string>,
  // Перенос из Excel
  importTitle: "Перенести таблицу из Excel",
  importLead:
    "Выделите в Excel всю таблицу вместе с шапкой и строкой «Подушка» над ней, скопируйте (Ctrl+C) и вставьте сюда (Ctrl+V). Или выберите файл .xlsx / .csv.",
  importPaste: "Вставьте таблицу сюда",
  importFile: "Выбрать файл",
  importSheetPick: "Лист",
  importNothing: "Здесь пока пусто — вставьте таблицу или выберите файл.",
  importColumns: "Что где",
  importRole: "Чем считать",
  importMonthCol: "месяц",
  importTotalCol: "Итог — только сверить",
  importSkip: "Не переносить",
  importCreate: "Создать «{name}»",
  importFound: "Нашлось: {months} мес. — с {from} по {to}, столбцов: {columns}.",
  importTotalsOk: "Итоги сошлись с Excel во всех {count} мес. — столбцы поняты правильно.",
  importTotalsBad:
    "Итоги не сошлись в {count} мес. (например, {month}: в Excel {file}, у нас {ours}). Проверьте, чем считаются столбцы.",
  importMarkers: "Над таблицей: {items}",
  importReplace:
    "Нынешняя таблица заменится этой. Передумаете — «Отменить перенос» вернёт её как была.",
  importGo: "Перенести",
  imported: "Таблица перенесена: {months} мес.",
  importBadFile: "Не получилось прочитать файл: {error}"
};

type Text = typeof RU;

const EN: Text = {
  ...RU,
  main: "Main",
  savings: "Savings",
  month: "Month",
  total: "Total",
  savingsTotal: "Savings total",
  sum: "Sum",
  average: "Average",
  addColumn: "Item",
  addColumnTitle: "Add an item — a new column",
  addMonth: "Month",
  addMonthBefore: "Earlier month",
  import: "Import from Excel",
  export: "Export to Excel",
  exported: "Sheet exported.",
  compare: "Compare with ledger",
  compareHint: "Below each number — what was actually spent in this category.",
  fact: "actual",
  undoImport: "Undo import",
  undone: "The sheet is back as it was before the import.",
  showHidden: "Hidden columns",
  fillDown: "Fill down",
  more: "More",
  filled: "Filled to the end of the sheet.",
  operations: "Operations in ledger",
  operationsFor: "Operations for {month}",
  emptyTitle: "Budget sheet by month",
  emptyLead:
    "Like Excel, only simpler: months as rows, spending items as columns. Opening balance and total are calculated for you.",
  emptyStep1: "Pick your items",
  emptyStep1Text:
    "Groceries, transport, rent — where the money goes. You can use your own categories.",
  emptyStep2: "Enter amounts",
  emptyStep2Text: "What you earn and plan to spend each month. Edit right in the cells later.",
  emptyStep3: "Watch the total",
  emptyStep3Text: "What is left at the end of the month — carried into the next one automatically.",
  emptyCreate: "Create a sheet",
  emptyStart: "Blank sheet",
  emptyImport: "Import my sheet from Excel",
  hint: "Double-click or type a digit to edit. Enter — down, Tab — right, Ctrl+V — paste a block from Excel, Ctrl+Z — undo.",
  barEmpty: "Click a cell and type an amount. Formulas work too: 20000+1500.",
  barCell: "{column} · {month}",
  barFact: "In ledger: {fact}",
  barOver: "over by {amount}",
  barUnder: "under by {amount}",
  barNextMonth: "To next month",
  barAuto: "Calculated automatically: {value}. Type a number to override.",
  barPlaceholder: "Number or formula",
  barInputLabel: "Input for the selected cell",
  sumTitle: "Now · {month}",
  sumNow: "Now",
  sumOpening: "At start",
  sumIncome: "Income",
  sumExpense: "Spending",
  sumTotal: "Left over",
  sumSavings: "In savings",
  shortfall: "In {month} the money runs out: total {amount}. Cut spending or add income.",
  runningOut: "The sheet ends in {count} mo. — add more months.",
  addMonths: "Months",
  addOne: "+1 month ahead",
  addThree: "+3 months ahead",
  addYear: "+12 months ahead",
  monthsAdded: "Months added: {count}.",
  today: "Go to current month",
  fillFromLedger: "Fill from ledger",
  fillFromLedgerHint:
    "Past months get what the ledger has recorded. Only empty cells of items that have a category.",
  fillFromLedgerDone: "Filled from ledger: {count}.",
  fillFromLedgerNothing:
    "Nothing to fill: items have no category or the ledger is empty for those months.",
  monthActions: "What to do with the month",
  monthOperations: "Operations for the month",
  copyFromPrev: "Copy numbers from last month",
  copied: "Copied: {count}.",
  copyNothing: "Nothing to copy from last month.",
  clearMonth: "Clear the month's numbers",
  cleared: "Cleared: {count}.",
  density: "Size",
  densityComfort: "Large",
  densityCompact: "Compact",
  help: "How it works",
  helpItems: [
    "A row is a month, a column is an item: what you spent or plan to spend.",
    "Italic means the sheet calculated it. Opening balance equals last month's total.",
    "Total = Opening + Income − Spending − To savings. It becomes next month's opening balance.",
    "Type a number or a formula: 20000+1500, =SUM(1000;2000), =45000*13%.",
    "Click an item name that has a category to see its operations in the ledger.",
    "The bottom rows show the sum and average of each item."
  ],
  helpLegend: "Legend",
  legendAuto: "calculated",
  legendIncome: "income",
  legendMinus: "shortfall",
  legendNow: "current month",
  wizTitle: "Create a sheet",
  wizLead: "Answer a few questions and the sheet builds itself. You can change everything later.",
  wizFrom: "Starting month",
  wizFromNow: "This month",
  wizFromAgo1: "Last month",
  wizFromAgo3: "3 months ago",
  wizFromAgo6: "Half a year ago",
  wizFromAgo12: "A year ago",
  wizMonths: "How many months",
  wizMonthsCount: "{count} mo.",
  wizOpening: "Money you have now",
  wizOpeningHint: "Everything on cards and in cash — the sheet starts from it.",
  wizIncome: "Monthly income",
  wizIncomeHint: "Salary and the rest. You can change any month later.",
  wizArticles: "Spending items",
  wizArticlesHint: "Tick what to track. On the right — planned monthly amount (optional).",
  wizMonthly: "per month",
  wizAll: "Select all",
  wizNone: "Clear all",
  wizSavings: "Track savings (a cushion)",
  wizSavingsOpening: "Already saved",
  wizHistory: "Fill past months from the ledger",
  wizHistoryHint: "For months before the current one we use what is recorded in the app.",
  wizCreate: "Create sheet",
  wizCreated: "Sheet ready: {months} months, items: {count}.",
  viewTable: "Table",
  viewMonths: "By month",
  monthPrev: "Previous month",
  monthNext: "Next month",
  monthTotalRow: "Left over",
  monthEmptyCell: "not filled",
  monthEditHint: "Tap an item to enter an amount.",
  kindHints: {
    opening: "How the month starts. Usually calculated from last month's total.",
    income: "Money coming in: salary, side jobs.",
    expense: "Money going out: groceries, transport, rent.",
    toSavings: "A transfer from main money to the cushion. Subtracted from the total.",
    fromSavings: "Taking money out of the cushion back to main money.",
    savingsOpening: "How much is in the cushion at the start of the month.",
    savingsIncome: "Deposit interest: the cushion grows, main money is not reduced.",
    note: "Just words — a comment on the month. Calculates nothing."
  },
  cellError: "Could not calculate: {error}",
  auto: "carried over from last month",
  save: "Save",
  clear: "Clear",
  cancel: "Cancel",
  close: "Close",
  delete: "Delete",
  column: "Column",
  columnNew: "New column",
  columnName: "Name",
  columnKind: "What it is",
  columnCategory: "Ledger category",
  noCategory: "No category",
  moveLeft: "Left",
  moveRight: "Right",
  hide: "Hide",
  unhide: "Show",
  deleteColumn: "Delete column",
  deleteColumnConfirm: "Delete column “{name}” and all its numbers?",
  deleteMonth: "Delete row",
  deleteMonthConfirm: "Delete {month} from the sheet?",
  targets: "Targets",
  addTarget: "Target",
  targetLabel: "Name",
  targetDefault: "Cushion",
  targetDate: "By date",
  targetAmount: "Amount",
  input: "Number or formula",
  inputHint: "Excel style works: 20000+1500, =SUM(1000;2000), =45000*13%",
  saved: "Saved.",
  pasted: "Pasted: {count}.",
  kinds: {
    opening: "Opening balance",
    income: "Income",
    expense: "Expense",
    toSavings: "To savings",
    fromSavings: "From savings",
    savingsOpening: "Savings at start",
    savingsIncome: "Deposit interest",
    note: "Note (text)"
  },
  importTitle: "Import a sheet from Excel",
  importLead:
    "Select the whole table in Excel with its header, copy (Ctrl+C) and paste here (Ctrl+V). Or choose an .xlsx / .csv file.",
  importPaste: "Paste the table here",
  importFile: "Choose file",
  importSheetPick: "Sheet",
  importNothing: "Nothing here yet — paste a table or choose a file.",
  importColumns: "Columns",
  importRole: "Treat as",
  importMonthCol: "month",
  importTotalCol: "Total — check only",
  importSkip: "Skip",
  importCreate: "Create “{name}”",
  importReplace:
    "The current sheet will be replaced. Changed your mind — “Undo import” brings it back.",
  importGo: "Import",
  imported: "Sheet imported: {months} months.",
  importBadFile: "Could not read the file: {error}"
};

export type SheetText = Text;

export function useSheetText() {
  const { locale } = useI18n();
  const words = locale === "en" ? EN : RU;
  const format = (template: string, values: Record<string, string | number> = {}) =>
    template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
  return { words, format, locale };
}

/** «2026-08» → «авг 2026». */
export function monthLabel(month: string, locale: string, style: "short" | "long" = "short") {
  const [year, index] = month.split("-").map(Number);
  const text = new Date(year, index - 1, 1)
    .toLocaleDateString(locale === "en" ? "en-GB" : "ru-RU", { month: style, year: "numeric" })
    .replace(/\s*г\.?$/, "")
    .replace(".", "");
  return text.charAt(0).toUpperCase() + text.slice(1);
}
